FROM rust:1.65.0

LABEL maintainer "Tapro Labs <kontakt@taprolabs.de>"

WORKDIR /app

RUN cargo install cargo-watch

# copy .env.docker only when we do not have .env
RUN test -f .env || cp .env.docker .env

EXPOSE 8000

CMD ["make", "dev"]
