version: '3.7'

networks:
  backend:
    driver: bridge

volumes:
  redis:
    driver: local
  rust_cache:
    driver: local
  yarn_cache:
    driver: local

services:
  redis:
    image: redis:7.0.8-alpine
    networks:
      - backend
    ports:
      - "9015:6379"
    volumes:
      - redis:/data

  workspace:
    build:
      dockerfile: Dockerfile.local
      context: .
    depends_on:
      - redis
    networks:
      - backend
    ports:
      - "9011:8000"
    volumes:
      - ./backend:/app
      - rust_cache:/usr/local/cargo

  frontend:
    image: node:18.14.1
    depends_on:
      - workspace
    ports:
      - "9010:3000"
    command: bash -c "yarn --cache-folder=/tmp/.local-yarn-cache && cd ./frontend && (test -f .env || cp .env.docker .env) && yarn dev"
    working_dir: /app
    volumes:
      - .:/app
      - yarn_cache:/tmp/.local-yarn-cache
      - /app/node_modules
      - /app/backend
      - /app/frontend/node_modules
