version: '3.7'

networks:
  backend:
    driver: bridge

volumes:
  redis:
    driver: local
  rust_cache:
    driver: local

services:
  redis:
    image: redis:7.0.3-alpine
    networks:
      - backend
    ports:
      - 9015:6379
    volumes:
      - redis:/data

  workspace:
    build:
      dockerfile: Dockerfile.local
      context: .
    depends_on:
      - redis
    networks:
      - backend
    ports:
      - 9011:8000
    volumes:
      - ./backend:/app
      - rust_cache:/usr/local/cargo

  frontend:
    image: node:14.20.1
    depends_on:
      - workspace
    environment:
      IN_DOCKER: 'yes'
    ports:
      - 9010:3000
    command: bash -c "yarn && yarn dev"
    working_dir: /app
    volumes:
      - ./frontend:/app
