FROM rust:1.68.2

LABEL maintainer "Tapro Labs <kontakt@taprolabs.de>"

WORKDIR /app

COPY ./backend/rust-toolchain.toml .
RUN cargo install cargo-watch

EXPOSE 8000

CMD ["/bin/bash", "-c", "(test -f .env || cp .env.docker .env) && make dev"]
