name: ots-server
version: 1.0.0
github: "tapro-labs/one-time-secret"
author: "Tapro Labs"
maintainer: "taprolabs@contact.de"

extra-source-files:
- README.md

dependencies:
  - base >= 4.9 && < 4.17
  - text >= 1.2 && < 2.1
  - servant >= 0.19 && < 0.20
  - servant-server >= 0.19 && < 0.20
  - wai >= 3.2 && < 3.3
  - wai-cors >= 0.2 && < 0.3
  - wai-extra >= 3.1 && < 3.2
  - warp >= 3.2 && < 3.3
  - aeson >= 2.0 && <= 2.1
  - hedis >= 0.15 && < 0.16
  - uuid >= 1.3 && < 1.4
  - random >= 1.2 && < 1.3
  - hslogger >= 1.3 && < 1.4
  - optparse-applicative >= 0.17 && < 0.18

executable:
  main: Main.hs
  source-dirs: src
  ghc-options: -Wall
