[default]
address = "127.0.0.1"
port = 8000
keep_alive = 5
read_timeout = 5
write_timeout = 5
limits = { form = "256 kB", json = "1 MiB" }

[debug]
log = "debug"
tls = { key = "../server_ssl/default.key", certs = "../server_ssl/default.crt" }

[docker]
address = "0.0.0.0"
log = "debug"

[release]
address = "0.0.0.0"
log = "critical"

